# Generated by Django 4.0 on 2021-12-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyData',
            fields=[
                ('FacultyId', models.TextField(max_length=8, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoggedInUsers',
            fields=[
                ('type', models.IntegerField()),
                ('ids', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('News', models.TextField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='PlacementsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('update', models.TextField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('rollNo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Course', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=10)),
                ('semester', models.IntegerField(default=1)),
                ('cgpa', models.FloatField(default=0.0)),
                ('credits', models.IntegerField(default=0)),
                ('isIcPc', models.BooleanField(default=False)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.CharField(max_length=8)),
                ('Subj1', models.CharField(max_length=50)),
                ('Subj2', models.CharField(max_length=50)),
                ('Subj3', models.CharField(max_length=50)),
                ('Subj4', models.CharField(max_length=50)),
                ('Subj5', models.CharField(max_length=50)),
            ],
        ),
    ]
