# Generated by Django 4.0 on 2022-01-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NITK', '0002_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
    ]
